# Generated by Django 2.2.19 on 2022-11-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eresh_token', models.TextField(unique=True, verbose_name='Токен в ERESH')),
                ('eresh_email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('eresh_id', models.PositiveIntegerField(verbose_name='ID в ERESH')),
                ('tg_user_id', models.PositiveIntegerField(verbose_name='ID в телеге')),
                ('tg_nickname', models.TextField(verbose_name='Логин в телеге')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
