# Generated by Django 2.2.19 on 2022-11-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eresh_token', models.TextField(unique=True, verbose_name='Токен в ERESH')),
                ('eresh_token_expires', models.DateTimeField(verbose_name='Время смерти токена')),
                ('eresh_email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('eresh_id', models.PositiveIntegerField(unique=True, verbose_name='ID в ERESH')),
                ('tg_user_id', models.PositiveIntegerField(unique=True, verbose_name='ID в телеге')),
                ('tg_nickname', models.TextField(unique=True, verbose_name='Логин в телеге')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='Балланс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
